/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.security.academicinternshipproject;

/**
 *
 * @author rokom
 */
public class CrawlerScriptingJP extends javax.swing.JPanel {

    private GUIManager guiManager;
    private WebCrawler currentCrawler;
    
    /**
     * Creates new form CrawlerScriptingJP
     */
    public CrawlerScriptingJP() {
        initComponents();
    }
    
    public void setGuiManager(GUIManager manager) {
        guiManager = manager;
    }
    
    public void setWebCrawler(WebCrawler crawler) {
        currentCrawler = crawler;
    }
    
    public WebCrawler getWebCrawler() {
        return currentCrawler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseLBL = new javax.swing.JLabel();
        commandCB = new javax.swing.JComboBox<>();
        addBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scriptTA = new javax.swing.JTextArea();
        inputTF = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 255));
        setName("crawlerScriptingJP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(610, 390));

        chooseLBL.setForeground(new java.awt.Color(255, 255, 255));
        chooseLBL.setText("Choose Command:");

        commandCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visit", "Search", "Write" }));

        addBTN.setText("Add Command");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        backBTN.setText("Back");
        backBTN.setName(""); // NOI18N
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        scriptTA.setColumns(20);
        scriptTA.setRows(5);
        jScrollPane1.setViewportView(scriptTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commandCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputTF)
                        .addGap(64, 64, 64)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(backBTN)
                .addGap(59, 59, 59)
                .addComponent(addBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(okBTN)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseLBL)
                        .addGap(29, 29, 29)
                        .addComponent(commandCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(okBTN)
                    .addComponent(backBTN))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        guiManager.setCurrentPanel(guiManager.findPanel("crawlerConfigJP"));
    }//GEN-LAST:event_backBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String commandToAdd = commandCB.getSelectedItem().toString();
        String object = inputTF.getText();
        currentCrawler.addCommand(commandToAdd + " " + object);
        scriptTA.setText("");
        int counter = 0;
        for (String command: currentCrawler.getCommands()) {
            counter++;
            scriptTA.append("Command " + String.valueOf(counter) + ": " + command + "\n");
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        ((CrawlerConfigJP)guiManager.findPanel("crawlerConfigJP")).writeCrawler();
        scriptTA.setText("Crawler ready to use.");   
        ((MainMenuJP)guiManager.findPanel("mainMenuJP")).loadCrawlers();
    }//GEN-LAST:event_okBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel chooseLBL;
    private javax.swing.JComboBox<String> commandCB;
    private javax.swing.JTextField inputTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBTN;
    private javax.swing.JTextArea scriptTA;
    // End of variables declaration//GEN-END:variables
}
