/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.security.academicinternshipproject;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author rokom
 * https://docs.oracle.com/javase/8/docs/api/java/io/ObjectOutputStream.html
 */
public class CrawlerConfigJP extends javax.swing.JPanel {

    private MainMenuForm mainMenuForm;
    /**
     * Creates new form CrawlerConfigJP
     */
    public CrawlerConfigJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        initComponents();
        scriptBTN.setEnabled(false);
    }
    
    private void populateFields() {
        if (mainMenuForm.isEditMode()) {
            nameTF.setText(mainMenuForm.getSelectedCrawler().getName());
            userAgentTF.setText(mainMenuForm.getSelectedCrawler().getUserAgent());
            crawlDelaySP.setValue(mainMenuForm.getSelectedCrawler().getCrawlDelay());
            scriptBTN.setEnabled(true);
        } else {
            nameTF.setText("");
            userAgentTF.setText("");
            crawlDelaySP.setValue(0);
            scriptBTN.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        nameLBL = new javax.swing.JLabel();
        crawlDelayLBL = new javax.swing.JLabel();
        userAgentTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        crawlDelaySP = new javax.swing.JSpinner();
        userAgentLBL = new javax.swing.JLabel();
        scriptBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 50, 50));
        setName("crawlerConfigJP"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        nameLBL.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL.setText("Name:");

        crawlDelayLBL.setForeground(new java.awt.Color(255, 255, 255));
        crawlDelayLBL.setText("Crawl Delay (seconds):");

        userAgentLBL.setForeground(new java.awt.Color(255, 255, 255));
        userAgentLBL.setText("User Agent:");

        scriptBTN.setText("Script Behaviour");
        scriptBTN.setEnabled(false);
        scriptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crawlDelayLBL)
                            .addComponent(userAgentLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crawlDelaySP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userAgentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(backBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scriptBTN)
                        .addGap(78, 78, 78)))
                .addComponent(okBTN)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAgentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userAgentLBL))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crawlDelayLBL)
                    .addComponent(crawlDelaySP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(okBTN)
                    .addComponent(scriptBTN))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Main Menu");
    }//GEN-LAST:event_backBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.getSelectedCrawler().setName(nameTF.getText());
        mainMenuForm.getSelectedCrawler().setUserAgent(userAgentTF.getText());
        mainMenuForm.getSelectedCrawler().setCrawlDelay(Integer.parseInt(crawlDelaySP.getValue().toString()));
        if (mainMenuForm.isEditMode())
            mainMenuForm.writeCrawler();
        scriptBTN.setEnabled(true);
    }//GEN-LAST:event_okBTNActionPerformed

    private void scriptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Crawler Scripting");
    }//GEN-LAST:event_scriptBTNActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        populateFields();
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel crawlDelayLBL;
    private javax.swing.JSpinner crawlDelaySP;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton okBTN;
    private javax.swing.JButton scriptBTN;
    private javax.swing.JLabel userAgentLBL;
    private javax.swing.JTextField userAgentTF;
    // End of variables declaration//GEN-END:variables
}
