/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.security.academicinternshipproject;

/**
 *
 * @author rokom
 */
public class CrawlerScriptingJP extends javax.swing.JPanel {

    private MainMenuForm mainMenuForm;
    private WebCrawler currentCrawler;
    private int selectedCommandIndex = -1;
    
    /**
     * Creates new form CrawlerScriptingJP
     */
    public CrawlerScriptingJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        initComponents();
    }
    
    public void setWebCrawler(WebCrawler crawler) {
        currentCrawler = crawler;
    }
    
    public WebCrawler getWebCrawler() {
        return currentCrawler;
    }
    
    public void populateFields() {
        int counter = 0;
        scriptTA.setText("");
        for (String command: currentCrawler.getCommands()) {
            counter++;
            scriptTA.append("Command " + String.valueOf(counter) + ": " + command + "\n");
        }
        // populate combo box with commands that have been added thus far
        if (currentCrawler != null)
            if (!currentCrawler.getName().equals("New Crawler...")) {
                counter = 0;
                editCB.removeAllItems();
                editCB.setEnabled(true);
                editCB.addItem("None");
                editCB.setSelectedItem("None");
                for (String command: currentCrawler.getCommands()) {
                    counter++;
                    editCB.addItem("Command " + counter);
                }
            }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandBG = new javax.swing.ButtonGroup();
        chooseLBL = new javax.swing.JLabel();
        commandCB = new javax.swing.JComboBox<>();
        addBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scriptTA = new javax.swing.JTextArea();
        inputTF = new javax.swing.JTextField();
        resultsRB = new javax.swing.JRadioButton();
        resultsCB = new javax.swing.JComboBox<>();
        urlhtmlRB = new javax.swing.JRadioButton();
        editLBL = new javax.swing.JLabel();
        editCB = new javax.swing.JComboBox<>();
        editBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        setName("crawlerScriptingJP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(610, 390));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        chooseLBL.setForeground(new java.awt.Color(255, 255, 255));
        chooseLBL.setText("Choose Command:");

        commandCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visit", "Search", "Text", "Attribute", "Write", "SQL", "Python" }));
        commandCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandCBActionPerformed(evt);
            }
        });

        addBTN.setText("Add Command");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        backBTN.setText("Back");
        backBTN.setName(""); // NOI18N
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        scriptTA.setColumns(20);
        scriptTA.setRows(5);
        jScrollPane1.setViewportView(scriptTA);

        inputTF.setEnabled(false);

        commandBG.add(resultsRB);
        resultsRB.setForeground(new java.awt.Color(255, 255, 255));
        resultsRB.setText("Search Results");
        resultsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsRBActionPerformed(evt);
            }
        });

        resultsCB.setEnabled(false);

        commandBG.add(urlhtmlRB);
        urlhtmlRB.setForeground(new java.awt.Color(255, 255, 255));
        urlhtmlRB.setText("URL / HTML");
        urlhtmlRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlhtmlRBActionPerformed(evt);
            }
        });

        editLBL.setForeground(new java.awt.Color(255, 255, 255));
        editLBL.setText("Edit Command:");

        editCB.setEnabled(false);
        editCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCBActionPerformed(evt);
            }
        });

        editBTN.setText("Edit Command");
        editBTN.setEnabled(false);
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultsRB)
                            .addComponent(urlhtmlRB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chooseLBL)
                                    .addComponent(commandCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultsCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputTF, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(backBTN)
                .addGap(59, 59, 59)
                .addComponent(addBTN)
                .addGap(35, 35, 35)
                .addComponent(editBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okBTN)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chooseLBL)
                            .addComponent(editLBL))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(commandCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(urlhtmlRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultsRB)
                        .addGap(17, 17, 17)
                        .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(okBTN)
                    .addComponent(backBTN)
                    .addComponent(editBTN))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Crawler Configuration");
    }//GEN-LAST:event_backBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        currentCrawler = mainMenuForm.getSelectedCrawler();
        System.out.println("Current crawler: " + currentCrawler.getName());
        currentCrawler.addCommand(composeCommand());
    }//GEN-LAST:event_addBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.writeCrawler();
        scriptTA.setText("Crawler ready to use.");   
    }//GEN-LAST:event_okBTNActionPerformed

    private void commandCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commandCBActionPerformed

    private void urlhtmlRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlhtmlRBActionPerformed
        // TODO add your handling code here:
        inputTF.setEnabled(true);
        resultsCB.setEnabled(false);
    }//GEN-LAST:event_urlhtmlRBActionPerformed

    private void resultsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsRBActionPerformed
        // TODO add your handling code here:
        inputTF.setEnabled(true);
        resultsCB.setEnabled(true);
        // get a list of results that actions can be performed on
        int counter = 0;
        resultsCB.removeAllItems();
        for (String command: currentCrawler.getCommands()) {
            counter++;
            CommandParser commandParser = new CommandParser(command);
            String action = commandParser.getAction();
            if (action.equals("Search") || action.equals("Text") || action.equals("Attribute"))
                resultsCB.addItem("Command #" + counter);
        }
    }//GEN-LAST:event_resultsRBActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        currentCrawler = mainMenuForm.getSelectedCrawler();
        System.out.println("Current crawler: " + currentCrawler.getName());
        editBTN.setVisible(false);
        if (!currentCrawler.getName().equals("New Crawler..."))
            populateFields();
    }//GEN-LAST:event_formAncestorAdded

    private void editCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCBActionPerformed
        // TODO add your handling code here:
        // find the command and parse it so it can be tweaked in the editor
        currentCrawler = mainMenuForm.getSelectedCrawler();
        editBTN.setVisible(true);
        int counter = 0;
        // clear input fields if "None" is selected
        if (editCB.getSelectedItem().equals("None")) {
            // placeholder
        }
        for (String command: currentCrawler.getCommands()) {
            counter++;
            resultsCB.removeAllItems();
            CommandParser commandParser = new CommandParser(command);
            if (commandParser.getAction().equals("Search") || commandParser.getAction().equals("Text") ||
                    commandParser.getAction().equals("Attribute"))
                resultsCB.addItem("Command #" + counter);
            if (editCB.getSelectedIndex() == counter) {
                commandCB.setSelectedItem(commandParser.getAction());
                inputTF.setEnabled(true);
                selectedCommandIndex = counter;
                if (commandParser.getSubjectNo() > -1) {
                    resultsCB.setEnabled(true);
                    resultsCB.setSelectedItem("Command #" + commandParser.getSubjectNo());
                    resultsRB.setSelected(true);
                    inputTF.setText(commandParser.getObject());
                } else {
                    urlhtmlRB.setSelected(true);
                    inputTF.setText(commandParser.getObject());
                }
            }
        }
        
    }//GEN-LAST:event_editCBActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        // TODO add your handling code here:
        currentCrawler = mainMenuForm.getSelectedCrawler();
        currentCrawler.editCommand(selectedCommandIndex, composeCommand());
    }//GEN-LAST:event_editBTNActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        scriptTA.setText("");
        int counter = 0;
        for (String command: currentCrawler.getCommands()) {
            counter++;
            scriptTA.append("Command " + String.valueOf(counter) + ": " + command + "\n");
        }
    }//GEN-LAST:event_formMouseClicked

    private String composeCommand() {
        String commandToAdd = commandCB.getSelectedItem().toString();
        String object = "";
        if (urlhtmlRB.isSelected())
            object = inputTF.getText();
        else {
            object = inputTF.getText();
            commandToAdd = resultsCB.getSelectedItem().toString() + " " + commandCB.getSelectedItem().toString();
        }
        return commandToAdd + " " + object;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel chooseLBL;
    private javax.swing.ButtonGroup commandBG;
    private javax.swing.JComboBox<String> commandCB;
    private javax.swing.JButton editBTN;
    private javax.swing.JComboBox<String> editCB;
    private javax.swing.JLabel editLBL;
    private javax.swing.JTextField inputTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBTN;
    private javax.swing.JComboBox<String> resultsCB;
    private javax.swing.JRadioButton resultsRB;
    private javax.swing.JTextArea scriptTA;
    private javax.swing.JRadioButton urlhtmlRB;
    // End of variables declaration//GEN-END:variables
}
