/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.security.academicinternshipproject;

import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author rokom
 */
public class DatabaseQueryJP extends javax.swing.JPanel {

    private MainMenuForm mainMenuForm;
    private boolean validDataType = false;
    /**
     * Creates new form DatabaseQueryJP
     */
    public DatabaseQueryJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        initComponents();
    }
    
    class SQLTableModel extends AbstractTableModel {
        
        private String[] columnNames;
        private CachedRowSet data;
        
        public SQLTableModel(String[] columnNames, CachedRowSet data) {
            this.columnNames = columnNames;
            this.data = data;
        }
        
        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        @Override
        public int getRowCount() {
            int rows = 0;
            // move cursor to the last row
            try {
                data.last();
                // the index of the last row represents the count
                rows = data.getRow();
                data.beforeFirst();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            return rows;
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if (data == null || rowIndex < 0 || rowIndex >= getRowCount())
                return "";
            try {
                data.absolute(rowIndex + 1);
                return data.getObject(columnIndex + 1);
            } catch (SQLException ex) {
                System.out.println(ex);
                return null;
            }
        }
        
    }
    
    private void loadTableData() {
            List<String> listData = new ArrayList<>();
            for (SQLTableInfo table: mainMenuForm.getDatabaseInfo().getTables()) {
                listData.add(table.getTableName());
            }
            String[] array = new String[listData.size()];
            for (int i = 0; i < array.length; i++) {
                array[i] = listData.get(i);
            }
            tableLS.setListData(array);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        selectLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLS = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTBL = new javax.swing.JTable();
        refreshBTN = new javax.swing.JButton();
        selectedColLBL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 50, 50));
        setPreferredSize(new java.awt.Dimension(610, 390));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        selectLBL.setForeground(new java.awt.Color(255, 255, 255));
        selectLBL.setText("Select Table:");

        tableLS.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tableLSValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tableLS);

        displayTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        displayTBL.setRowSelectionAllowed(false);
        displayTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayTBLMouseClicked(evt);
            }
        });
        displayTBL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                displayTBLPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(displayTBL);

        refreshBTN.setText("Refresh Schema");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        selectedColLBL.setForeground(new java.awt.Color(255, 255, 255));
        selectedColLBL.setText("Selected column:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectLBL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(refreshBTN)
                                    .addComponent(backBTN))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedColLBL)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okBTN)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(selectLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBTN)
                    .addComponent(selectedColLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(okBTN))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Sentiment Analysis");
    }//GEN-LAST:event_backBTNActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        // load database schema if the user has already input their username and password
        if (!mainMenuForm.isSqlCredentialsRequired()) 
            mainMenuForm.loadDatabaseSchema();
    }//GEN-LAST:event_formAncestorAdded

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // TODO add your handling code here:
        if (mainMenuForm.loadDatabaseSchema()) {
            loadTableData();
            displaySelectedTableSchema();
        }
        
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void tableLSValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tableLSValueChanged
        // TODO add your handling code here:
        System.out.println("Selected table: " + tableLS.getSelectedValue());
        displaySelectedTableSchema();
    }//GEN-LAST:event_tableLSValueChanged

    private void displayTBLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_displayTBLPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_displayTBLPropertyChange

    private void displayTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayTBLMouseClicked
        // TODO add your handling code here:
        // extract selected column name
        int colIndex = displayTBL.getSelectedColumn();
        if (colIndex >= 0) {
            String selectedColumn = displayTBL.getColumnName(colIndex);
            System.out.println("Selected column: " + selectedColumn);
            selectedColLBL.setText("Selected column: " + selectedColumn);
            // establish column type; natural language types are required for processing
            SQLColumnInfo colInfo = mainMenuForm.getDatabaseInfo().findColumn(tableLS.getSelectedValue(), selectedColumn);
            System.out.println("Data type: " + colInfo.getTypeName());
            if (colInfo.getTypeName().equals("CHAR") || colInfo.getTypeName().equals("VARCHAR")
                    || colInfo.getTypeName().equals("LONGNVARCHAR") || colInfo.getTypeName().equals("BLOB")
                    || colInfo.getTypeName().equals("LONGVARCHAR") || colInfo.getTypeName().equals("NCHAR")
                    || colInfo.getTypeName().equals("TEXT")) {
                validDataType = true;
            }
            else
                validDataType = false;
        }
    }//GEN-LAST:event_displayTBLMouseClicked

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        if (validDataType) {
            mainMenuForm.setSelectedColumnName(displayTBL.getColumnName(displayTBL.getSelectedColumn()));
            mainMenuForm.setSelectedTableName(tableLS.getSelectedValue());
            System.out.println("Selection accepted.");
            mainMenuForm.setIsAnalysingTable(true);
            mainMenuForm.displayPanel("Sentiment Analysis");
        }
        else 
            JOptionPane.showMessageDialog(null, "Unexpected data type for NLP! Please select text data.");
    }//GEN-LAST:event_okBTNActionPerformed

    private void displaySelectedTableSchema() {
        // retrieve the selected table's schema first
        if (mainMenuForm.getDatabaseInfo() != null) {
            for (SQLTableInfo info: mainMenuForm.getDatabaseInfo().getTables()) {
                if (info.getTableName().equals(tableLS.getSelectedValue())) {
                    String[] colNames = new String[info.getColumns().size()];
                    Object[][] rowData = new Object[2][info.getColumns().size()];
                    mainMenuForm.returnTableData(info.getTableName());
                    // extract column names
                    for (int i = 0; i < info.getColumns().size(); i++) {
                        colNames[i] = info.getColumns().get(i).getColumnName();
                        System.out.println("Column name: " + colNames[i]);
                    }
                    SQLTableModel tableModel = new SQLTableModel(colNames, mainMenuForm.getCrs());
                    // remove existing table model
                    if (displayTBL.getModel() != null)
                        if (displayTBL.getCellEditor() != null)
                            displayTBL.getCellEditor().cancelCellEditing();              
                    displayTBL.setModel(tableModel);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JTable displayTBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okBTN;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JLabel selectLBL;
    private javax.swing.JLabel selectedColLBL;
    private javax.swing.JList<String> tableLS;
    // End of variables declaration//GEN-END:variables
}
