/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 * https://www.geeksforgeeks.org/java/java-joptionpane/
 */
package com.security.academicinternshipproject;

import javax.swing.JOptionPane;

/**
 *
 * @author rokom
 */
public class DeleteCrawlerJP extends javax.swing.JPanel {
    
    private MainMenuForm mainMenuForm;

    /**
     * Creates new form DeleteCrawlerJP
     */
    public DeleteCrawlerJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        abortBTN = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        crawlerLS = new javax.swing.JList<>();

        setBackground(new java.awt.Color(50, 50, 50));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Select crawler to delete");

        abortBTN.setText("Abort");
        abortBTN.addActionListener(this::abortBTNActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        jScrollPane1.setViewportView(crawlerLS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abortBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLBL)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abortBTN)
                    .addComponent(Delete))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        mainMenuForm.loadCrawlers(crawlerLS);
    }//GEN-LAST:event_formAncestorAdded

    private void abortBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel(mainMenuForm.getPreviousPanelName());
    }//GEN-LAST:event_abortBTNActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you wish to delete the highlighted crawler?", "Confirmation", JOptionPane.YES_NO_OPTION);
        // delete selected crawler
        if (choice == JOptionPane.YES_OPTION) {
            mainMenuForm.deleteCrawler(crawlerLS.getSelectedIndex());
            JOptionPane.showMessageDialog(null, "Crawler deleted!");
        }
        mainMenuForm.loadCrawlers(crawlerLS);
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton abortBTN;
    private javax.swing.JList<String> crawlerLS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
