/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 * https://stackoverflow.com/questions/12684072/eofexception-when-reading-files-with-objectinputstream
 */
package com.security.academicinternshipproject;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;

/**
 *
 * @author rokom
 */
public class MainMenuJP extends javax.swing.JPanel {
    
    private GUIManager guiManager;
    private ArrayList<WebCrawler> crawlerList = new ArrayList<>();

    /**
     * Creates new form MainMenuJP
     */
    public MainMenuJP() {
        initComponents();
        // load crawlers
        loadCrawlers();
    }
    
    public void setGuiManager(GUIManager manager) {
        guiManager = manager;
    }
    
    public ArrayList<WebCrawler> getCrawlerList() {
        return crawlerList;
    }
    
    public void loadCrawlers() {
        crawlersCB.removeAllItems();
        try {
            FileInputStream crawlers = new FileInputStream("crawlers.dat");
            try {
                ObjectInputStream ois = new ObjectInputStream(crawlers);
                crawlersCB.setEnabled(true);
                while (true) {
                    try {
                        crawlerList.add((WebCrawler)ois.readObject());
                    } catch (EOFException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        break;
                    }
                }
                for (WebCrawler crawler: crawlerList) {
                    crawlersCB.addItem(crawler.getName());
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
            crawlersCB.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        crawlBTN = new javax.swing.JButton();
        configBTN = new javax.swing.JButton();
        crawlersCB = new javax.swing.JComboBox<>();
        selectCrawlerLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTA = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 255));
        setName("mainMenuJP"); // NOI18N

        backBTN.setText("Back");

        okBTN.setText("OK");

        crawlBTN.setText("Crawl");
        crawlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlBTNActionPerformed(evt);
            }
        });

        configBTN.setText("Configure Crawler");
        configBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configBTNActionPerformed(evt);
            }
        });

        crawlersCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        crawlersCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlersCBActionPerformed(evt);
            }
        });

        selectCrawlerLBL.setForeground(new java.awt.Color(255, 255, 255));
        selectCrawlerLBL.setText("Select Crawler:");

        statusTA.setEditable(false);
        statusTA.setColumns(20);
        statusTA.setLineWrap(true);
        statusTA.setRows(5);
        jScrollPane1.setViewportView(statusTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBTN)
                        .addGap(88, 88, 88)
                        .addComponent(crawlBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(configBTN)
                        .addGap(41, 41, 41)
                        .addComponent(okBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crawlersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectCrawlerLBL))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(selectCrawlerLBL)
                        .addGap(18, 18, 18)
                        .addComponent(crawlersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(okBTN)
                    .addComponent(crawlBTN)
                    .addComponent(configBTN))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configBTNActionPerformed
        // TODO add your handling code here:
        guiManager.setCurrentPanel(guiManager.findPanel("crawlerConfigJP"));
    }//GEN-LAST:event_configBTNActionPerformed

    private void crawlersCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlersCBActionPerformed
        // TODO add your handling code here:
        statusTA.setText("");
        for (WebCrawler crawler: crawlerList) {
            if (crawlersCB.getSelectedItem().toString().equals(crawler.getName())) {
                statusTA.append("Name: " + crawler.getName() + "\n");
                statusTA.append("User Agent: " + crawler.getUserAgent() + "\n");
                statusTA.append("Crawl Delay: " + crawler.getCrawlDelay() + "\n");
                int counter = 0;
                for (String command: crawler.getCommands()) {
                    counter++;
                    statusTA.append("Command " + String.valueOf(counter) + ": " + command + "\n");
                }
            }
        }
    }//GEN-LAST:event_crawlersCBActionPerformed

    private void crawlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlBTNActionPerformed
        // TODO add your handling code here:
        for (WebCrawler crawler: crawlerList) {
            if (crawlersCB.getSelectedItem().toString().equals(crawler.getName())) {
                statusTA.setText("");
                Playwright playwright = Playwright.create();
                JSoupParser parser = new JSoupParser();
                Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions()
                .setSlowMo(crawler.getCrawlDelay() * 1000)
                //.setHeadless(false)
            );
                Page page = null;
                BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                .setUserAgent(crawler.getUserAgent())
                .setLocale("en-ie"));
                for (String command: crawler.getCommands()) {
                    if (command.startsWith("Visit")) {
                        page = browser.newPage();
                        page.navigate(command.substring(6));
                        statusTA.append("Visiting " + command.substring(6) + "\n");
                        statusTA.append(page.content());
                    }
                    else if (command.startsWith("Search")) {
                        ArrayList<String> response = parser.searchDocument(page.content(), command.substring(7));
                        crawler.setHtmlResponses(response);
                        statusTA.append("Searching...\n");
                        for (String result: crawler.getHtmlResponses()) {
                            statusTA.append(result + "\n");
                        }
                    }
                    else if (command.startsWith("Write")) {
                        File paragraphs = new File("text.txt");
                        statusTA.append("Writing...\n");
                        try {
                            FileWriter writer = new FileWriter(paragraphs);
                            for (String p: crawler.getHtmlResponses()) {
                                writer.write(p + "\n");
                            }
                            writer.close();
                            statusTA.append("Write complete!\n");
                        } catch (IOException ex) {
                            System.out.println(ex);
                        }
                    }
                }
                playwright.close();
            }
        }
    }//GEN-LAST:event_crawlBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton configBTN;
    private javax.swing.JButton crawlBTN;
    private javax.swing.JComboBox<String> crawlersCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel selectCrawlerLBL;
    private javax.swing.JTextArea statusTA;
    // End of variables declaration//GEN-END:variables
}
