/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 * https://stackoverflow.com/questions/12684072/eofexception-when-reading-files-with-objectinputstream
 * https://huggingface.co/blog/sentiment-analysis-python
 */
package com.security.academicinternshipproject;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import java.util.List;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rokom
 */
public class MainMenuJP extends javax.swing.JPanel {
    
    private GUIManager guiManager;
    private ArrayList<WebCrawler> crawlerList = new ArrayList<>();
    private MySQLConnector mysql;
    private boolean sqlCredentialsRequired = false;
    private boolean newCrawler = false;
    private WebCrawler selectedCrawler = new WebCrawler();

    /**
     * Creates new form MainMenuJP
     */
    public MainMenuJP() {
        initComponents();
        // load crawlers
        loadCrawlers();
    }
    
    public void setGuiManager(GUIManager manager) {
        guiManager = manager;
    }
    
    public ArrayList<WebCrawler> getCrawlerList() {
        return crawlerList;
    }
    
    public void setSQLCredentialsRequired(boolean value) {
        sqlCredentialsRequired = value;
    }
    
    public boolean getIfNewCrawler() {
        return newCrawler;
    }
    
    public WebCrawler getSelectedCrawler() {
        return selectedCrawler;
    }
    
    public void loadCrawlers() {
        crawlersCB.removeAllItems();
        try {
            FileInputStream crawlers = new FileInputStream("crawlers.dat");
            try {
                ObjectInputStream ois = new ObjectInputStream(crawlers);
                while (true) {
                    try {
                        crawlerList.add((WebCrawler)ois.readObject());
                    } catch (EOFException | ClassNotFoundException ex) {
                        //ex.printStackTrace();
                        break;
                    }
                }
                for (WebCrawler crawler: crawlerList) {
                    if (crawler != null)
                        crawlersCB.addItem(crawler.getName());
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        crawlersCB.addItem("New Crawler...");
        if (crawlersCB.getSelectedItem().toString().equals("New Crawler...")) {
            System.out.println("Creating new crawler...");
            newCrawler = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        crawlBTN = new javax.swing.JButton();
        configBTN = new javax.swing.JButton();
        crawlersCB = new javax.swing.JComboBox<>();
        selectCrawlerLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTA = new javax.swing.JTextArea();
        responsesLBL = new javax.swing.JLabel();
        responsesCB = new javax.swing.JComboBox<>();
        dbSettingsBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        setName("mainMenuJP"); // NOI18N

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        crawlBTN.setText("Crawl");
        crawlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlBTNActionPerformed(evt);
            }
        });

        configBTN.setText("Configure Crawler");
        configBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configBTNActionPerformed(evt);
            }
        });

        crawlersCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        crawlersCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlersCBActionPerformed(evt);
            }
        });

        selectCrawlerLBL.setForeground(new java.awt.Color(255, 255, 255));
        selectCrawlerLBL.setText("Select Crawler:");

        statusTA.setEditable(false);
        statusTA.setColumns(20);
        statusTA.setLineWrap(true);
        statusTA.setRows(5);
        jScrollPane1.setViewportView(statusTA);

        responsesLBL.setForeground(new java.awt.Color(255, 255, 255));
        responsesLBL.setText("View HTML Responses:");

        responsesCB.setEnabled(false);
        responsesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsesCBActionPerformed(evt);
            }
        });

        dbSettingsBTN.setText("Database Settings");
        dbSettingsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbSettingsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backBTN)
                        .addGap(31, 31, 31)
                        .addComponent(crawlBTN)
                        .addGap(35, 35, 35)
                        .addComponent(configBTN)
                        .addGap(63, 63, 63)
                        .addComponent(dbSettingsBTN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(crawlersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectCrawlerLBL)))
                                    .addComponent(responsesLBL))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(responsesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(selectCrawlerLBL)
                        .addGap(18, 18, 18)
                        .addComponent(crawlersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(responsesLBL)
                        .addGap(18, 18, 18)
                        .addComponent(responsesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(crawlBTN)
                    .addComponent(configBTN)
                    .addComponent(dbSettingsBTN))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configBTNActionPerformed
        // TODO add your handling code here:
        guiManager.setCurrentPanel(guiManager.findPanel("crawlerConfigJP"));
    }//GEN-LAST:event_configBTNActionPerformed

    private void crawlersCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlersCBActionPerformed
        // TODO add your handling code here:
        statusTA.setText("");
        for (WebCrawler crawler: crawlerList) {
            if (crawler != null)
            if (crawlersCB.getSelectedItem().toString().equals(crawler.getName())) {
                selectedCrawler = crawler;
                statusTA.append("Name: " + crawler.getName() + "\n");
                statusTA.append("User Agent: " + crawler.getUserAgent() + "\n");
                statusTA.append("Crawl Delay: " + crawler.getCrawlDelay() + "\n");
                int counter = 0;
                for (String command: crawler.getCommands()) {
                    counter++;
                    statusTA.append("Command " + String.valueOf(counter) + ": " + command + "\n");
                    CommandParser commandParser = new CommandParser(command);
                    if (commandParser.getAction().equals("SQL")) {
                        sqlCredentialsRequired = true;
                        }
                    }
                }
            if (crawlersCB.getSelectedItem().toString().equals("New Crawler...")) {
                System.out.println("Creating new crawler...");
                selectedCrawler = new WebCrawler();
                newCrawler = true;
            }
        }
    }//GEN-LAST:event_crawlersCBActionPerformed

    private void crawlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlBTNActionPerformed
        // TODO add your handling code here:
        String baseUrl = "";
        if (sqlCredentialsRequired) {
            guiManager.setCurrentPanel(guiManager.findPanel("SQLCredentialsJP"));
            return;
        }   
        for (WebCrawler crawler: crawlerList) {
            if (crawlersCB.getSelectedItem().toString().equals(crawler.getName())) {
                statusTA.setText("");
                Playwright playwright = Playwright.create();
                JSoupParser parser = new JSoupParser();
                Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions()
                .setSlowMo(crawler.getCrawlDelay() * 1000)
                //.setHeadless(false)
            );
                // initialise browser
                Page page = null;
                BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                .setUserAgent(crawler.getUserAgent())
                .setLocale("en-ie"));
                
                for (String command: crawler.getCommands()) {
                    ArrayList<String> response = new ArrayList<>();
                    ArrayList<String> results = new ArrayList<>();
                    CommandParser commandParser = new CommandParser(command);
                    command = commandParser.getAction();
                    System.out.println("Command #" + commandParser.getCommandNo() + ": " + command);
                    System.out.println("Object Number: " + commandParser.getSubjectNo());
                    // if operating on a previous command's results
                    if (commandParser.getSubjectNo() > -1) {
                        int resultsIndex = commandParser.getSubjectNo() - 1;
                        // find the final results of a particular operation by looping through the crawler in reverse direction
                        for (int i = crawler.getHtmlResponses().size() - 1; i >= 0; i--) {
                            System.out.println("Loop index: " + i);
                            // never evaluates true if subject number is -1
                            if (crawler.getHtmlResponses().get(i).getCommandNo() == commandParser.getSubjectNo()) {
                                resultsIndex = i;
                                break;
                            }
                        }
                        for (String result: crawler.getHtmlResponses().get(resultsIndex).getResults()) {
                            results.add(result);
                        }
                    }
                    else
                        results.add(commandParser.getObject());
                    int loopCounter = 0;
                    for (String result: results) {
                        loopCounter++;
                        if (result.length() > 32)
                            System.out.println("Result # " + loopCounter + ": " + result.substring(0, 31));
                        else
                            System.out.println("Result # " + loopCounter + ": " + result);
                        if (command.equals("Visit")) {
                            page = browser.newPage();
                            if (result.startsWith("/"))
                                result = baseUrl + result;
                            page.navigate(result);
                            if (baseUrl.equals(""))
                                baseUrl = page.url().substring(0, page.url().length() - 1);
                            response.add(page.content());
                            //crawler.addHtmlResponse(new SearchResult(response, commandParser.getCommandNo()));
                        }
                        else if (command.equals("Search")) {
                            response.addAll(parser.searchDocument(crawler.getHtmlResponses().getLast().getResults(), result));
                            //crawler.addHtmlResponse(new SearchResult(response, commandParser.getCommandNo()));
                        }
                        else if (command.equals("Text")) {
                            response.add(parser.getTextFromDocument(result));
                            //crawler.addHtmlResponse(new SearchResult(response, commandParser.getCommandNo()));
                        }
                        else if (command.equals("Attribute")) {
                            response.addAll(parser.getAttributesFromDocument(result, commandParser.getObject()));
                            //crawler.addHtmlResponse(new SearchResult(response, commandParser.getCommandNo()));
                        }
                        else if (command.equals("SQL")) {
                            File databaseSettings = new File("credentials.txt");
                            try {
                                BufferedReader reader = new BufferedReader(new FileReader(databaseSettings));
                                List<String> credentials = new ArrayList<>();
                                String line;
                                while ((line = reader.readLine()) != null) {
                                    credentials.add(line);
                                    System.out.println("Reading line: " + line);
                                }
                                mysql = new MySQLConnector(credentials.get(0), Integer.parseInt(credentials.get(1)), credentials.get(2),
                                    String.valueOf(((SQLCredentialsJP)guiManager.findPanel("SQLCredentialsJP")).getUsername()),
                                    String.valueOf(((SQLCredentialsJP)guiManager.findPanel("SQLCredentialsJP")).getPassword()));
                                // prevent credentials lingering in memory
                                ((SQLCredentialsJP)guiManager.findPanel("SQLCredentialsJP")).eraseCredentials();
                                response.add(mysql.getResult());
                            } catch (FileNotFoundException | ClassNotFoundException ex) {
                                System.out.println(ex);
                            } catch (IOException ex) {
                                System.out.println(ex);
                            }
                        }
                        else if (command.startsWith("Write")) {
                            File paragraphs = new File(result);
                            try {
                                FileWriter writer = new FileWriter(paragraphs);
                                for (String toWrite: crawler.getHtmlResponses().getLast().getResults()) {
                                    writer.write(toWrite + "\n");
                                }
                                writer.close();
                            } catch (IOException ex) {
                                System.out.println(ex);
                            }
                        }   
                        else if (command.startsWith("Python")) {
                        // invoke Python script
                            ProcessBuilder pb = new ProcessBuilder("cmd", "/c", "start", "python", "-u", commandParser.getObject())
                                    .inheritIO();
                            try {
                                Process process = pb.start();
                            } catch (IOException ex) {
                                Logger.getLogger(MainMenuForm.class.getName()).log(Level.SEVERE, null, ex);
                            }                   
                        }
                    }
                    if (!commandParser.getAction().equals("Python") && !commandParser.getAction().equals("Write"))
                        crawler.addHtmlResponse(new SearchResult(response, commandParser.getCommandNo()));
                    statusTA.append("Executing command " + commandParser.getAction() + "\n");
                    for (String line: response) {
                        statusTA.append(line + "\n");
                    }
                }
                // add HTML responses to combo box
                int counter = -1;
                responsesCB.setEnabled(true);
                responsesCB.removeAllItems();
                for (SearchResult result: crawler.getHtmlResponses()) {
                    counter++;
                    responsesCB.addItem("Response " + counter);
                }
                playwright.close();
            }
        }
    }//GEN-LAST:event_crawlBTNActionPerformed

    private void responsesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsesCBActionPerformed
        // TODO add your handling code here:
        statusTA.setText("");
        // look up crawler
        String targetName = crawlersCB.getSelectedItem().toString();
        WebCrawler target = null;
        for (WebCrawler crawler: crawlerList) {
            if (crawler.getName().equals(targetName))
                target = crawler;
        }
        for (String result: target.getHtmlResponses().get(responsesCB.getSelectedIndex()).getResults()) {
            statusTA.append(result + "\n");
        }
    }//GEN-LAST:event_responsesCBActionPerformed

    private void dbSettingsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbSettingsBTNActionPerformed
        // TODO add your handling code here:
        guiManager.setCurrentPanel(guiManager.findPanel("databaseSettingsJP"));
    }//GEN-LAST:event_dbSettingsBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        guiManager.setCurrentPanel(guiManager.findPanel("homeLandingJP"));
    }//GEN-LAST:event_backBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton configBTN;
    private javax.swing.JButton crawlBTN;
    private javax.swing.JComboBox<String> crawlersCB;
    private javax.swing.JButton dbSettingsBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> responsesCB;
    private javax.swing.JLabel responsesLBL;
    private javax.swing.JLabel selectCrawlerLBL;
    private javax.swing.JTextArea statusTA;
    // End of variables declaration//GEN-END:variables
}
