/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 * https://stackoverflow.com/questions/12684072/eofexception-when-reading-files-with-objectinputstream
 * https://huggingface.co/blog/sentiment-analysis-python
 * https://www.w3schools.com/sql/sql_insert.asp
 * https://www.w3schools.com/java/java_regex.asp
 * https://docs.oracle.com/javase/tutorial/uiswing/components/menu.html
 * https://docs.oracle.com/javase/8/docs/api/javax/swing/SwingUtilities.html#invokeLater-java.lang.Runnable-
 */
package com.security.academicinternshipproject;

import com.security.academicinternshipproject.swingworkers.WebCrawlerGUIWorker;
import javax.swing.SwingUtilities;
import static javax.swing.SwingWorker.StateValue.DONE;
import static javax.swing.SwingWorker.StateValue.PENDING;
import static javax.swing.SwingWorker.StateValue.STARTED;

/**
 *
 * @author rokom
 */
public class MainMenuJP extends javax.swing.JPanel {
    
    private MainMenuForm mainMenuForm;
    private MySQLConnector mysql;
    private WebCrawlerGUIWorker crawlerWorker;

    /**
     * Creates new form MainMenuJP
     */
    public MainMenuJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        mysql = mainMenuForm.getMySQL();
        // add menu bar
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        crawlBTN = new javax.swing.JButton();
        configBTN = new javax.swing.JButton();
        crawlersCB = new javax.swing.JComboBox<>();
        selectCrawlerLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTA = new javax.swing.JTextArea();
        responsesLBL = new javax.swing.JLabel();
        responsesCB = new javax.swing.JComboBox<>();
        dbSettingsBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 50, 50));
        setName("mainMenuJP"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        crawlBTN.setText("Crawl");
        crawlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlBTNActionPerformed(evt);
            }
        });

        configBTN.setText("Configure Crawler");
        configBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configBTNActionPerformed(evt);
            }
        });

        crawlersCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        crawlersCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlersCBActionPerformed(evt);
            }
        });

        selectCrawlerLBL.setForeground(new java.awt.Color(255, 255, 255));
        selectCrawlerLBL.setText("Select Crawler:");

        statusTA.setEditable(false);
        statusTA.setColumns(20);
        statusTA.setLineWrap(true);
        statusTA.setRows(5);
        jScrollPane1.setViewportView(statusTA);

        responsesLBL.setForeground(new java.awt.Color(255, 255, 255));
        responsesLBL.setText("View HTML Responses:");

        responsesCB.setEnabled(false);
        responsesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsesCBActionPerformed(evt);
            }
        });

        dbSettingsBTN.setText("Database Settings");
        dbSettingsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbSettingsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backBTN)
                        .addGap(31, 31, 31)
                        .addComponent(crawlBTN)
                        .addGap(35, 35, 35)
                        .addComponent(configBTN)
                        .addGap(63, 63, 63)
                        .addComponent(dbSettingsBTN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(crawlersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectCrawlerLBL)))
                                    .addComponent(responsesLBL))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(responsesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(selectCrawlerLBL)
                        .addGap(18, 18, 18)
                        .addComponent(crawlersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(responsesLBL)
                        .addGap(18, 18, 18)
                        .addComponent(responsesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(crawlBTN)
                    .addComponent(configBTN)
                    .addComponent(dbSettingsBTN))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configBTNActionPerformed
        // TODO add your handling code here:        
        mainMenuForm.displayPanel("Crawler Configuration");
    }//GEN-LAST:event_configBTNActionPerformed

    private void crawlersCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlersCBActionPerformed
        // TODO add your handling code here:
        statusTA.setText("");
        for (WebCrawler crawler: mainMenuForm.getWebCrawlers()) {
            if (crawlersCB.getSelectedItem().toString().equals(crawler.getName())) {
                mainMenuForm.setSelectedCrawler(crawler);
                System.out.println("Selected Crawler: " + crawler.getName());
                //crawler.printInfo();
                statusTA.append("Name: " + crawler.getName() + "\n");
                statusTA.append("User Agent: " + crawler.getUserAgent() + "\n");
                statusTA.append("Crawl Delay: " + crawler.getCrawlDelay() + "\n");
                int counter = 0;
                for (String command: crawler.getCommands()) {
                    counter++;
                    statusTA.append("Command " + String.valueOf(counter) + ": " + command + "\n");
                    CommandParser commandParser = new CommandParser(command);
//                    if (commandParser.getAction().equals("SQL")) {
//                        mainMenuForm.setSQLCredentialsRequired(true);
//                        }
                       }
                }
            if (crawlersCB.getSelectedItem().toString().equals("New Crawler...")) {
                mainMenuForm.setSelectedCrawler(new WebCrawler());
                mainMenuForm.setEditMode(false);
            }
        }
    }//GEN-LAST:event_crawlersCBActionPerformed

    private void crawlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlBTNActionPerformed
        // TODO add your handling code here:
        if (mainMenuForm.isSqlCredentialsRequired()) {
            mainMenuForm.displayPanel("SQL Settings");
        }
        else
            crawlerWorker.execute();
    }//GEN-LAST:event_crawlBTNActionPerformed

    private void responsesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsesCBActionPerformed
        // TODO add your handling code here:
            if (crawlerWorker.getState() != STARTED ) {
            statusTA.setText("");
            // look up crawler
            String targetName = crawlersCB.getSelectedItem().toString();
            WebCrawler target = null;
            for (WebCrawler crawler: mainMenuForm.getWebCrawlers()) {
                if (crawler.getName().equals(targetName))
                    target = crawler;
            }
            for (String result: target.getHtmlResponses().get(responsesCB.getSelectedIndex()).getResults()) {
                statusTA.append(result + "\n");
            }
        }
    }//GEN-LAST:event_responsesCBActionPerformed

    private void dbSettingsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbSettingsBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Database Settings");
    }//GEN-LAST:event_dbSettingsBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Landing");
    }//GEN-LAST:event_backBTNActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        // initialise worker for the first time
        if (crawlerWorker == null)
        crawlerWorker = new WebCrawlerGUIWorker(mainMenuForm,
            mysql, statusTA, crawlersCB, responsesCB);
        // do not load crawlers if a script is currently being executed
        if (crawlerWorker.getState() == PENDING) {
            mainMenuForm.loadCrawlers(crawlersCB);
            System.out.println("Last selected crawler: " + mainMenuForm.getLastSelectedCrawlerName());
            // find previously selected crawler if reloading form
            SwingUtilities.invokeLater(() -> {
                System.out.println("Invoking...");
                if (mainMenuForm.getLastSelectedCrawlerName() != null)
                if (!mainMenuForm.getLastSelectedCrawlerName().equals(crawlersCB.getSelectedItem().toString()))
                for (int i = 0; i < crawlersCB.getItemCount(); i++) {
                    System.out.println("Looping");
                    if (crawlersCB.getItemAt(i).equals(mainMenuForm.getLastSelectedCrawlerName())) {
                        System.out.println("Match found");
                        crawlersCB.setSelectedItem(mainMenuForm.getLastSelectedCrawlerName());
                    }
                }});
            // reinitialise worker if done
            if (crawlerWorker.getState() == DONE)
                crawlerWorker = new WebCrawlerGUIWorker(mainMenuForm,
                    mysql, statusTA, crawlersCB, responsesCB);
            System.out.println("Crawler State: " + crawlerWorker.getState());
        }
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        // memorise the last selected crawler
        mainMenuForm.setLastSelectedCrawlerName(crawlersCB.getSelectedItem().toString());
    }//GEN-LAST:event_formAncestorRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton configBTN;
    private javax.swing.JButton crawlBTN;
    private javax.swing.JComboBox<String> crawlersCB;
    private javax.swing.JButton dbSettingsBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> responsesCB;
    private javax.swing.JLabel responsesLBL;
    private javax.swing.JLabel selectCrawlerLBL;
    private javax.swing.JTextArea statusTA;
    // End of variables declaration//GEN-END:variables
}
