/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.security.academicinternshipproject;

import ai.djl.MalformedModelException;
import ai.djl.repository.zoo.ModelNotFoundException;
import ai.djl.translate.TranslateException;
import com.security.academicinternshipproject.swingworkers.SentimentAnalysisGUIWorker;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rokom
 */
public class SentimentAnalysisJP extends javax.swing.JPanel {
    
    private MainMenuForm mainMenuForm;
    private List<Integer> positiveScores;
    private List<Integer> negativeScores;
    
    /**
     * Creates new form SentimentAnalysisJP
     */
    public SentimentAnalysisJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        initComponents();
        positivePB.setForeground(Color.green);
        negativePB.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        inputLBL = new javax.swing.JLabel();
        inputTF = new javax.swing.JTextField();
        modelLBL = new javax.swing.JLabel();
        runBTN = new javax.swing.JButton();
        positiveLBL = new javax.swing.JLabel();
        negativeLBL = new javax.swing.JLabel();
        positivePB = new javax.swing.JProgressBar();
        negativePB = new javax.swing.JProgressBar();
        pValueLBL = new javax.swing.JLabel();
        nValueLBL = new javax.swing.JLabel();
        responsesCB = new javax.swing.JComboBox<>();
        responsesLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTA = new javax.swing.JTextArea();
        queryBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 50, 50));
        setPreferredSize(new java.awt.Dimension(610, 390));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        titleLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Sentiment Analysis");

        inputLBL.setForeground(new java.awt.Color(255, 255, 255));
        inputLBL.setText("Enter Text:");

        modelLBL.setForeground(new java.awt.Color(255, 255, 255));
        modelLBL.setText("Current Model:");

        runBTN.setText("Run");
        runBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBTNActionPerformed(evt);
            }
        });

        positiveLBL.setForeground(new java.awt.Color(255, 255, 255));
        positiveLBL.setText("Probability of Positive Sentiment:");

        negativeLBL.setForeground(new java.awt.Color(255, 255, 255));
        negativeLBL.setText("Probability of Negative Sentiment:");

        positivePB.setOpaque(true);

        negativePB.setOpaque(true);

        pValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        pValueLBL.setText("Positive");

        nValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        nValueLBL.setText("Negative");

        responsesCB.setEnabled(false);
        responsesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsesCBActionPerformed(evt);
            }
        });

        responsesLBL.setForeground(new java.awt.Color(255, 255, 255));
        responsesLBL.setText("HTML Responses:");

        statusTA.setEditable(false);
        statusTA.setColumns(20);
        statusTA.setRows(5);
        statusTA.setWrapStyleWord(true);
        jScrollPane1.setViewportView(statusTA);

        queryBTN.setText("Query Database");
        queryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(titleLBL))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modelLBL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputLBL))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(responsesLBL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(responsesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                        .addComponent(queryBTN)))
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(44, 44, 44)))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runBTN)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positiveLBL)
                            .addComponent(negativeLBL))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(positivePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(negativePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pValueLBL)
                            .addComponent(nValueLBL))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLBL)
                    .addComponent(responsesLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryBTN))
                .addGap(26, 26, 26)
                .addComponent(modelLBL)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(positivePB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(positiveLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pValueLBL))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(negativePB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negativeLBL)
                    .addComponent(nValueLBL))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(runBTN))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Main Menu");
    }//GEN-LAST:event_backBTNActionPerformed

    private void runBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBTNActionPerformed
        // TODO add your handling code here:
        SentimentAnalysisGUIWorker worker = new SentimentAnalysisGUIWorker(mainMenuForm,
        statusTA, inputTF, positivePB, negativePB, pValueLBL, nValueLBL);
        worker.execute();
//        try {
//            if (!statusTA.getText().equals(""))
//                mainMenuForm.getSentimentAnalyser().predict(statusTA.getText());
//            else if (!mainMenuForm.isAnalysingSQLTable())
//                mainMenuForm.getSentimentAnalyser().predict(inputTF.getText());
//            else {
//                // predict sentiment for each table row
//                int index = 0;
//                positiveScores = new ArrayList<>();
//                negativeScores = new ArrayList<>();
//                while (mainMenuForm.getCrs().next()) {
//                    index++;
//                    System.out.println("Analysing row " + index + " out of " + mainMenuForm.getCrs().size()); 
//                    if (mainMenuForm.getCrs().getString(mainMenuForm.getSelectedColumnName()) != null &&
//                            !mainMenuForm.getCrs().getString(mainMenuForm.getSelectedColumnName()).trim().isEmpty()) {
//                        mainMenuForm.getSentimentAnalyser().predict(mainMenuForm.getCrs().getString(mainMenuForm.getSelectedColumnName()));
//                        positiveScores.add((int)(mainMenuForm.getSentimentAnalyser().getClassifications().get("Positive").getProbability() * 100));
//                        negativeScores.add((int)(mainMenuForm.getSentimentAnalyser().getClassifications().get("Negative").getProbability() * 100));
//                    } else
//                        System.out.println("Skipping row...");
//                }
//                mainMenuForm.getCrs().close();
//                mainMenuForm.setIsAnalysingTable(false);
//                inputTF.setText("");
//            }
//            displayAnalysisResults();
//        } catch (MalformedModelException ex) {
//            System.out.println(ex);
//        } catch (ModelNotFoundException ex) {
//            System.out.println(ex);
//        } catch (IOException ex) {
//            System.out.println(ex);
//        } catch (TranslateException ex) {
//            System.out.println(ex);
//        } catch (SQLException ex) {
//            System.out.println(ex);
//        }
    }//GEN-LAST:event_runBTNActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        modelLBL.setText("Current Model: " + mainMenuForm.getSentimentAnalyser().getModelUrl());
        // add HTML responses if they exist
        if (!mainMenuForm.getSelectedCrawler().getHtmlResponses().isEmpty()) {
            mainMenuForm.populateComboBoxWithHTMLResponses(responsesCB, mainMenuForm.getSelectedCrawler());
            responsesCB.setVisible(true);
            responsesLBL.setVisible(true);
        } else {
            responsesCB.setVisible(false);
            responsesLBL.setVisible(false);
        }
        // fill in text field if using SQL query
        if (mainMenuForm.getSelectedColumnName() != null)
            inputTF.setText("SELECT " + mainMenuForm.getSelectedColumnName() + " FROM " + mainMenuForm.getSelectedTableName());
    }//GEN-LAST:event_formAncestorAdded

    private void responsesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsesCBActionPerformed
        // TODO add your handling code here:
        // populate text area with crawler output
        statusTA.setText("");
        for (String result: mainMenuForm.getSelectedCrawler().getHtmlResponses().get(responsesCB.getSelectedIndex()).getResults()) {
            statusTA.append(result + "\n");
        }
    }//GEN-LAST:event_responsesCBActionPerformed

    private void queryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Database Query");
    }//GEN-LAST:event_queryBTNActionPerformed

    public void displayAnalysisResults() {
//        if (!mainMenuForm.isAnalysingSQLTable()) {
//        positivePB.setValue((int)(mainMenuForm.getSentimentAnalyser().getClassifications().get("Positive").getProbability() * 100));
//        negativePB.setValue((int)(mainMenuForm.getSentimentAnalyser().getClassifications().get("Negative").getProbability() * 100));
//        } else {
//            positivePB.setValue(computeAggregateScore((ArrayList<Integer>) positiveScores));
//            negativePB.setValue(computeAggregateScore((ArrayList<Integer>) negativeScores));
//            positiveScores.clear();
//            negativeScores.clear();
//        }
//        pValueLBL.setText(String.valueOf(mainMenuForm.getSentimentAnalyser().getClassifications().get("Positive").getProbability()));
//        nValueLBL.setText(String.valueOf(mainMenuForm.getSentimentAnalyser().getClassifications().get("Negative").getProbability()));
    }
    
//    public int computeAggregateScore(ArrayList<Integer> values) {
//        int finalValue = 0;
//        int denominator = 0;
//        for (int value: values) {
//            denominator++;
//            System.out.println("Value " + denominator + ": "+ value);
//            finalValue += value;
//        }
//        System.out.println("Final value: " + finalValue + "/" + denominator);
//        return finalValue / denominator;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel inputLBL;
    private javax.swing.JTextField inputTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modelLBL;
    private javax.swing.JLabel nValueLBL;
    private javax.swing.JLabel negativeLBL;
    private javax.swing.JProgressBar negativePB;
    private javax.swing.JLabel pValueLBL;
    private javax.swing.JLabel positiveLBL;
    private javax.swing.JProgressBar positivePB;
    private javax.swing.JButton queryBTN;
    private javax.swing.JComboBox<String> responsesCB;
    private javax.swing.JLabel responsesLBL;
    private javax.swing.JButton runBTN;
    private javax.swing.JTextArea statusTA;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
