/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
    https://docs.oracle.com/javase/tutorial/uiswing/components/passwordfield.html
 */
package com.security.academicinternshipproject;

import java.util.Arrays;

/**
 *
 * @author rokom
 */
public class SQLCredentialsJP extends javax.swing.JPanel {
    
    private GUIManager guiManager;
    private char[] username;
    private char[] password;
    private boolean credentialsSet = false;

    /**
     * Creates new form SQLCredentialsJP
     */
    public SQLCredentialsJP() {
        initComponents();
    }
    
    public char[] getUsername() {
        return username;
    }
    
    public char[] getPassword() {
        return password;
    }
    
    public boolean getAreCredentialsSet() {
        return credentialsSet;
    }
    
    public void setGuiManager(GUIManager manager) {
        guiManager = manager;
    }
    
    public void eraseCredentials() {
        Arrays.fill(username, '0');
        Arrays.fill(password, '0');
        credentialsSet = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        usernameLBL = new javax.swing.JLabel();
        passwordLBL = new javax.swing.JLabel();
        usernamePF = new javax.swing.JPasswordField();
        passwordPF = new javax.swing.JPasswordField();
        okBTN = new javax.swing.JButton();
        abortBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        setName("SQLCredentialsJP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(614, 390));

        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("SQL Credentials Input");

        usernameLBL.setForeground(new java.awt.Color(255, 255, 255));
        usernameLBL.setText("Enter username: ");

        passwordLBL.setForeground(new java.awt.Color(255, 255, 255));
        passwordLBL.setText("Enter password:");

        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        abortBTN.setText("Abort");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLBL)
                    .addComponent(passwordLBL))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernamePF, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(passwordPF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(titleLBL)
                .addGap(249, 249, 249))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(abortBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okBTN)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleLBL)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLBL)
                    .addComponent(usernamePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLBL)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBTN)
                    .addComponent(abortBTN))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        username = usernamePF.getPassword();
        password = passwordPF.getPassword();
        credentialsSet = true;
        usernamePF.setText("");
        passwordPF.setText("");
        ((MainMenuJP)(guiManager.findPanel("mainMenuJP"))).setSQLCredentialsRequired(false);
        guiManager.setCurrentPanel(guiManager.findPanel("mainMenuJP"));
    }//GEN-LAST:event_okBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortBTN;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel usernameLBL;
    private javax.swing.JPasswordField usernamePF;
    // End of variables declaration//GEN-END:variables
}
