package com.security.academicinternshipproject;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 * https://docs.oracle.com/javase/tutorial/uiswing/components/table.html#renderer
 * https://www.tutorialspoint.com/article/java-program-to-append-a-row-to-a-jtable-in-java-swing
 * https://docs.oracle.com/javase/tutorial/uiswing/components/table.html#modelchange
 * https://dev.mysql.com/doc/refman/9.7/en/create-table.html
 */

/**
 *
 * @author rokom
 */
public class SQLDatabaseJP extends javax.swing.JPanel {

    private MainMenuForm mainMenuForm;
    private boolean reentrancyGuard = false;
    private int primaryKeyIndex = -1;
    /**
     * Creates new form SQLDatabaseJP
     */
    public SQLDatabaseJP(MainMenuForm mainMenuForm) {
        this.mainMenuForm = mainMenuForm;
        initComponents();
        configureTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        columnsTBL = new javax.swing.JTable();
        abortBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 50, 50));
        setPreferredSize(new java.awt.Dimension(610, 390));

        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Create New Table");

        nameLBL.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL.setText("Table Name:");

        columnsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Column Name", "Data Type", "Primary Key", "Auto-Increment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableColumn typeColumn = columnsTBL.getColumnModel().getColumn(1);
        JComboBox<String> typeCB = new JComboBox<>(dataTypes);
        typeColumn.setCellEditor(new DefaultCellEditor(typeCB));
        jScrollPane1.setViewportView(columnsTBL);

        abortBTN.setText("Abort");
        abortBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortBTNActionPerformed(evt);
            }
        });

        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        addBTN.setText("Add Row");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("Delete Row");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(titleLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLBL)
                                .addGap(31, 31, 31)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abortBTN)
                                .addGap(67, 67, 67)
                                .addComponent(addBTN)
                                .addGap(49, 49, 49)
                                .addComponent(deleteBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addComponent(okBTN)))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abortBTN)
                    .addComponent(okBTN)
                    .addComponent(addBTN)
                    .addComponent(deleteBTN))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abortBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortBTNActionPerformed
        // TODO add your handling code here:
        mainMenuForm.displayPanel("Database Settings");
    }//GEN-LAST:event_abortBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        // check if SQL credentials have been set
        if (mainMenuForm.getUsername() == null || mainMenuForm.getPassword() == null) {
            mainMenuForm.displayPanel("SQL Settings");
            return;
        }
        MySQLConnector sql = mainMenuForm.getMySQL();
        List<String> credentials = new ArrayList<>();
        String tableRow = "";
        String sqlStatement = "CREATE TABLE " + nameTF.getText() + "(";
        credentials = mainMenuForm.getSQLCredentials();
        // get table row and column details
        DefaultTableModel model = (DefaultTableModel)columnsTBL.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            tableRow = "";
            for (int j = 0; j < model.getColumnCount(); j++) {
                // do not pass "true" or "false" to the SQL statement
                if (model.getValueAt(i, j) != null && j != 2 && j != 3) {
                    tableRow += model.getValueAt(i, j).toString() + " ";
                    // specify default length if using varchar
                    if (j == 1)
                        if(model.getValueAt(i, j) == "VARCHAR" || model.getValueAt(i, j) == "VARBINARY")
                            tableRow += "(255)";
                }
                // if the current column is the primary key one
                if (j == 2 && model.getValueAt(i, j) != null) {
                    if ((boolean)model.getValueAt(i, j))
                        tableRow += "PRIMARY KEY";
                }
                // append the auto-increment modifier
                if (j == 3 && model.getValueAt(i, j) != null) {
                    if ((boolean)model.getValueAt(i, j))
                        tableRow += " AUTO_INCREMENT";
                }
            }
            tableRow = tableRow.trim();
            if (i != model.getRowCount() - 1)
                tableRow += ",";    
            sqlStatement += tableRow;
        }
        sqlStatement += ");";
        System.out.println("SQL Statement: " + sqlStatement);
        try {             
            sql = new MySQLConnector(credentials.get(0), Integer.parseInt(credentials.get(1)), credentials.get(2), String.valueOf(mainMenuForm.getUsername()), String.valueOf(mainMenuForm.getPassword()), sqlStatement);
            // wipe input fields
            nameTF.setText("");
            
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_okBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)columnsTBL.getModel();
        Object[] row = {null, null, null, null};
        model.addRow(row);
    }//GEN-LAST:event_addBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)columnsTBL.getModel();
        // prevent an out of bounds error
        if (model.getRowCount() > 0)
            model.removeRow(model.getRowCount() - 1);
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void configureTable() {
        DefaultTableModel model = (DefaultTableModel)columnsTBL.getModel();
        model.addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent e) {
                if (reentrancyGuard) {
                    // exit method
                    reentrancyGuard = false;
                    return;
                }
                // check if primary key has already been set
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (model.getValueAt(i, 2) != null) {
                        if ((boolean)model.getValueAt(i, 2) == true) {
                            // record the primary key index if selecting it for the first time
                            if (primaryKeyIndex == -1) {
                                primaryKeyIndex = i;
                            }
                            if (i != primaryKeyIndex && primaryKeyIndex > -1) {
                                // remove the check on the other box
                                int oldIndex = primaryKeyIndex;
                                primaryKeyIndex = i;
                                reentrancyGuard = true;
                                model.setValueAt(false, oldIndex, 2);
                            }
                        }
                    }
                    // remove the check on Auto-Increment if the database column is not
                    // a primary key
                    if (model.getValueAt(i, 3) != null) {
                        if ((boolean)model.getValueAt(i, 2) == false && (boolean)model.getValueAt(i, 3) == true) {
                            reentrancyGuard = true;
                            model.setValueAt(false, i, 3);                    
                        }
                    }
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortBTN;
    private javax.swing.JButton addBTN;
    private javax.swing.JTable columnsTBL;
    private String[] dataTypes = {"INT", "BIGINT", "VARCHAR", "TEXT", "DATE", "DATETIME", "DECIMAL", "FLOAT", "BOOLEAN", "TIMESTAMP"};
    private javax.swing.JButton deleteBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
