/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 * https://stackoverflow.com/questions/527719/how-to-add-hyperlink-in-jlabel
 * https://stackoverflow.com/questions/26749495/customize-detault-html-link-color-in-java-swing
 * https://docs.oracle.com/javase/tutorial/uiswing/events/windowlistener.html
 */
package com.security.academicinternshipproject.helpmenu;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author rokom
 */
public class AboutForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AboutForm.class.getName());

    /**
     * Creates new form AboutForm
     */
    public AboutForm() {
        initComponents();
        descriptionTA.setFocusable(false);
        descriptionTA.getCaret().setVisible(false);
        addHoverEffectToButtons(getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJP = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        okBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        repoLBL = new javax.swing.JLabel();
        linkLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainJP.setBackground(new java.awt.Color(51, 51, 255));
        mainJP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("About");

        okBTN.setText("OK");
        okBTN.addActionListener(this::okBTNActionPerformed);

        descriptionTA.setEditable(false);
        descriptionTA.setColumns(20);
        descriptionTA.setRows(5);
        descriptionTA.setText("Nascrawler is a desktop application developed in Java as\npart of an academic internship module. It is powered by such\ntechnologies as Playwright, DJL and MySQL. For further info,\nplease visit the below web page:");
        jScrollPane1.setViewportView(descriptionTA);

        repoLBL.setForeground(new java.awt.Color(255, 255, 255));
        repoLBL.setText("Git Repository:");

        linkLBL.setForeground(new java.awt.Color(255, 255, 255));
        linkLBL.setText("<html><a style=\"color: yellow;\" href=\"https://github.com/davidbconstantin/academic-internship\">Click Here To Open Git Repo</a></html>");
        linkLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLBLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainJPLayout = new javax.swing.GroupLayout(mainJP);
        mainJP.setLayout(mainJPLayout);
        mainJPLayout.setHorizontalGroup(
            mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okBTN)
                    .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
            .addGroup(mainJPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addComponent(repoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        mainJPLayout.setVerticalGroup(
            mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleLBL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repoLBL)
                    .addComponent(linkLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(okBTN)
                .addGap(20, 20, 20))
        );

        getContentPane().add(mainJP, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLBLMouseClicked
        // TODO add your handling code here:
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            desktop.browse(new URI("https://github.com/davidbconstantin/academic-internship"));
        } catch (IOException | URISyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_linkLBLMouseClicked

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_okBTNActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AboutForm().setVisible(true));
    }
    
        // iterate through every component adding hover effects
    private void addHoverEffectToButtons(Container container) {
        for (Component c: container.getComponents()) {
            if (c instanceof javax.swing.JButton button) 
                addHoverEffect(button);
            // use recursion to add events to nested buttons
            else if (c instanceof Container nestedContainer) 
                addHoverEffectToButtons(nestedContainer);
        }
    }
    
    // add mouse hover event to buttons
    private void addHoverEffect(javax.swing.JButton button) {
        button.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(Color.yellow);
                button.setForeground(Color.blue);
                repaint();
            }
            
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(Color.white);
                button.setForeground(Color.black);
                repaint();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel linkLBL;
    private javax.swing.JPanel mainJP;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel repoLBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
